# Generated by Django 6.0.6 on 2026-06-18 17:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('INTERVIEWER', 'Interviewer'), ('CANDIDATE', 'Candidate')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(help_text='The date and time when the interview session is scheduled')),
                ('duration_minutes', models.PositiveIntegerField(help_text='The duration of the interview session in minutes')),
                ('candidate', models.ForeignKey(help_text='The candidate attending the session', limit_choices_to={'role': 'CANDIDATE'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_sessions', to=settings.AUTH_USER_MODEL)),
                ('interviewer', models.ForeignKey(help_text='The interviewer conducting the session', limit_choices_to={'role': 'INTERVIEWER'}, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(help_text='The text of the interview question')),
                ('difficulty_level', models.CharField(help_text='The difficulty level of the question (e.g., Easy, Medium, Hard)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the question was created')),
                ('session', models.ForeignKey(help_text='The interview session to which the question belongs', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='djangoPracticeApp.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript', models.TextField(help_text="The transcript of the candidate's response")),
                ('sentiment_score', models.FloatField(help_text="The sentiment score of the candidate's response")),
                ('is_currect', models.BooleanField(help_text="Indicates whether the candidate's response is correct")),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text="The date and time when the candidate's response was submitted")),
                ('question_id', models.ForeignKey(help_text='The interview question to which the response belongs', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='djangoPracticeApp.interviewquestion')),
                ('session_id', models.ForeignKey(help_text='The interview session to which the response belongs', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='djangoPracticeApp.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter the job title', max_length=100)),
                ('description', models.TextField(help_text='Enter the job description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the job position was created')),
                ('created_by', models.ForeignKey(help_text='The user who created the job position', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='job_position',
            field=models.ForeignKey(help_text='The job position for which the interview session is scheduled', on_delete=django.db.models.deletion.CASCADE, to='djangoPracticeApp.jobposition'),
        ),
    ]
