# Generated by Django 6.0.6 on 2026-06-18 18:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoPracticeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='google_meet_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript', models.TextField(help_text="The transcript of the candidate's responses during the interview session")),
                ('sentiment_score', models.FloatField(help_text="The overall sentiment score of the candidate's responses")),
                ('communication_score', models.FloatField(help_text="The communication score of the candidate's responses")),
                ('problem_solving_score', models.FloatField(help_text="The problem-solving score of the candidate's responses")),
                ('technical_knowledge_score', models.FloatField(help_text="The technical knowledge score of the candidate's responses")),
                ('interview_session', models.ForeignKey(help_text='The interview session for which the evaluation report is generated', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_reports', to='djangoPracticeApp.interviewsession')),
            ],
        ),
    ]
