# Generated by Django 6.0.6 on 2026-06-18 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoPracticeApp', '0002_interviewsession_google_meet_url_evaluationreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateresponse',
            old_name='is_currect',
            new_name='is_correct',
        ),
        migrations.RenameField(
            model_name='candidateresponse',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='candidateresponse',
            old_name='session_id',
            new_name='session',
        ),
        migrations.AlterField(
            model_name='candidateresponse',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the response was submitted'),
        ),
        migrations.AlterField(
            model_name='evaluationreport',
            name='interview_session',
            field=models.OneToOneField(help_text='The interview session for which the evaluation report is generated', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_report', to='djangoPracticeApp.interviewsession'),
        ),
    ]
